apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  REACT_APP_API_URL: "http://backend:5000"
  REACT_APP_MONGODB_URI: "mongodb://mongodb:27017/audiodb"
  REACT_APP_POSTGRES_URI: "postgresql://postgres:postgres@postgres:5432/audiodb" 