apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb:27017/audiodb"
  MONGODB_ROOT_USERNAME: "admin"
  MONGODB_ROOT_PASSWORD: "admin123"
  POSTGRES_URI: "postgresql://postgres:postgres@postgres:5432/audiodb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres" 