apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  API_URL: {{ printf "http://%s-service:%d" .Values.backend.name .Values.backend.port | quote }}
  MONGODB_URI: {{ .Values.backend.env.MONGODB_URI | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  LEVEL_DB_NAME: {{ .Values.backend.env.LEVEL_DB_NAME | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }} 