apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audio-app.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | b64enc }}
  MONGODB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc }} 