apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGODB_USER: {{ .Values.mongodb.auth.username | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }} 