apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: patches/resource-limits.yaml
  - path: patches/replicas.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - FLASK_ENV=production
      - DEBUG=false

commonLabels:
  environment: prod 