apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: audio-app
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "audio-app.example.com"
  gateways:
  - audio-app-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: {{ .Release.Name }}-backend
        port:
          number: 5000
        subset: v1
      weight: 90
    - destination:
        host: {{ .Release.Name }}-backend
        port:
          number: 5000
        subset: v2
      weight: 10
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-frontend
        port:
          number: 80 