apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  API_URL: "http://backend:5000"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/admin"
  DB_NAME: "app_db"
  LEVEL_DB_NAME: "level_database"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379" 